[flags]
store = "redis"
verbose = false

[web]
username = "admin"
password = "123"

[apps]
[apps.myapp]
description = "myapp"
root = "/Users/huwl/myapp"
prefix = "myapp"
tmpl = ".env.example"
dest = ".env"
cmd = "nginx -s reload"

[apps.myapp2]
description = "myapp2"
root = "/Users/huwl/myapp2"
tmpl = ".env.example"
cmd = ""

[store]
[store.redis]
host = "127.0.0.1"
port = 6379
db = 0
password = ""

[store.mysql]
host = "127.0.0.1"
port = 6379
database = "econfig"
username = "root"
password = "dev"
